### ISSUE TITLE
Support Angular Monorepo using NX

### ISSUE THREAD

**Issue by diegohoyos** [chr33z/vscode-lingua#82]
I was using this extension for quite some time in a monorepo project using Nx (https://nx.dev/)
Starting with version 15 of Nx they adopted a configuration structure where angular.json file is not required, so after upgrade my project to NX 15 the extension is no longer working. Please consider to support Nx workspace adding a similiar validation for nx.json + ngx-translate module.

**Comment by chr33z** [comment]
Hi!

Thank you for your feedback! This would be a nice addition. I currently have no project with nx workspaces but, as this seems the way to go in the future, I will put this on my feature list!

**Comment by vkukurba** [comment]
Hi @chr33z I have faced the same issue.
In **NX** (15.7.0 +) instead of storing the configuration for every project in a single large **angular.json** file at the root, the configuration is split into multiple **project.json** [More details here](https://nx.dev/more-concepts/nx-and-angular).

So the `isNgxTranslateProject` method is not able to find angular.json. Looks like that is the reason why plugin does not work for NX 15.7.0 + 
Probably, that method can be extended with additional logic to check if project is NX (has nx.json file that contains @nrwl/angular or smth like that)
What do you think?

@diegohoyos I found temporary workaround. I've added empty angular.json file into .vscode folder, it can be added to the root as it fails to build and serve etc.

**Comment by chr33z** [comment]
@vkukurba Thanks for your feedback. Could you setup a sample project that I can use for testing a fix?

**Comment by vkukurba** [comment]
> @vkukurba Thanks for your feedback. Could you setup a sample project that I can use for testing a fix?

Try to use this one
https://github.com/vkukurba/nx-ng-translate-sample

**Comment by chr33z** [comment]
Hey @diegohoyos and @vkukurba 

I just releases a new version that enables lingua for NX workspaces. Thank you for providing a sample project. 

Do you think it would be helpful to have seperate translation files for each separate app in this workspace instead of a global one?

**Comment by chr33z** [comment]
@vkukurba 

I guess this is also a question of whether ngx-translate event supports multiple apps in a nx-project with different translation files. I did not find anything in their docs.

**Comment by diegohoyos** [comment]
@chr33z thanks for the new version. Related to support a different file per application that would be a nice addition. In my case I have only one global file but technically you can have specific http loader for each app and load different files so support a .lingua file at app folder level would be required for that scenario.
